# Generated by Django 5.1.2 on 2024-10-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0002_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forum.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forum.user_info')),
            ],
        ),
    ]
