# Generated by Django 5.1.2 on 2024-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forum', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collections',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
